kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-pv-volume
  namespace: first-dev
  labels:
    type: local
    app: web-dev
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-pv-claim
  namespace: first-dev
  labels:
    app: web-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

